Repository helsing-ai/buffrs, pull requests merged in 2023-10, with the labels that each got.

#126 Allows building registry
  Cargo.lock
  Cargo.toml
  registry/Cargo.toml
  registry/Proto.lock
  registry/src/proto.rs
Labels: complexity::low, component::registry, priority::low, type::fix

#103 Improve Errors using `miette`
  Cargo.lock
  Cargo.toml
  src/command.rs
  src/credentials.rs
  src/errors.rs
  src/generator.rs
  src/lib.rs
  src/lock.rs
  src/main.rs
  src/manifest.rs
  src/package.rs
  src/registry/artifactory.rs
  src/registry/local.rs
  src/registry/mod.rs
Labels: datamodel, type::style, component::cli, priority::high, complexity::high, type::refactoring, type::idea

#124 Use serde_typename crate for DigestAlgorithm
  src/lock.rs
Labels: complexity::low, type::refactoring, priority::low

#106 Clean up imports.
  src/command.rs
  src/generator.rs
  src/lock.rs
  src/registry/local.rs
  src/registry/mod.rs
Labels: complexity::low, type::style, type::refactoring, type::idea

#144 Check for existence of PackageStore when creating new
  src/command.rs
  src/generator.rs
  src/lib.rs
  src/package.rs
Labels: complexity::low, type::refactoring, priority::low

#149 Fail CI if unit test coverage is lower than threshold.
  .github/workflows/ci.yml
Labels: complexity::low, type::idea, priority::low

#150 Refactors src/package.rs into multiple modules.
  src/package.rs
  src/package/compressed.rs
  src/package/name.rs
  src/package/store.rs
  src/package/type.rs
Labels: complexity::low, component::cli, type::refactoring

#131 Refactor the `command` module
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  registry/Cargo.toml
  src/command.rs
  src/context.rs
  src/lib.rs
  src/main.rs
  src/manifest.rs
  src/package/mod.rs
  src/package/store.rs
  src/registry/local.rs
  tests/cmd/login/stdout.log
  tests/cmd/package/out/lib-0.0.1.tgz
Labels: complexity::low, type::style, component::cli, type::refactoring, priority::medium

#151 Refactors digest-related code in `src/lock.rs`
  Cargo.lock
  Cargo.toml
  src/lock.rs
  src/lock/digest.rs
Labels: complexity::low, component::cli, type::refactoring, priority::low

#153 Document `buffrs lint`
  docs/src/SUMMARY.md
  docs/src/commands/buffrs-lint.md
  docs/src/commands/index.md
  docs/src/reference/index.md
  docs/src/reference/package-name-spec.md
  docs/src/reference/protocol-buffer-rules.md
Labels: component::cli, priority::high, docs::book

#104 Rebase Nix flake PR
  .github/workflows/ci.yml
  .gitignore
  flake.lock
  flake.nix
Labels: complexity::low, integration, priority::medium

#130 Protobuf validation
  Cargo.lock
  Cargo.toml
  src/command.rs
  src/lib.rs
  src/main.rs
  src/package/store.rs
  src/validation.rs
  src/validation/data.rs
  src/validation/data/entity.rs
  src/validation/data/enum.rs
  src/validation/data/message.rs
  src/validation/data/package.rs
  src/validation/data/packages.rs
  src/validation/data/service.rs
  src/validation/parse.rs
  src/validation/rules.rs
  src/validation/rules/file_name.rs
  src/validation/rules/ident_casing.rs
  src/validation/rules/package_name.rs
  src/validation/serde.rs
  src/validation/violation.rs
  tests/data/parsing/addressbook.json
  tests/data/parsing/addressbook.proto
  tests/data/parsing/books.json
  tests/data/parsing/books.proto
Labels: component::cli, component::registry, complexity::high, type::feature, type::idea, priority::medium

#158 Update package name length constraints
  src/package/name.rs
Labels: component::cli, priority::high, complexity::high, type::fix
