Repository helsing-ai/buffrs, pull requests merged in 2023-11, with the labels that each got.

#160 Removes unused crates
  Cargo.lock
  Cargo.toml
Labels: complexity::low, component::cli, priority::low, type::fix

#164 Allow code gen when only protos exist
  src/generator.rs
Labels: complexity::low, component::cli, priority::medium, type::fix

#165 Improve error message for unpinned versions of dependencies
  docs/src/commands/buffrs-add.md
  docs/src/getting-started/first-steps.md
  src/registry/mod.rs
Labels: complexity::low, component::cli, docs::project, priority::medium, type::fix

#161 Remove ring dependency
  Cargo.lock
  Cargo.toml
  src/lock.rs
  src/lock/digest.rs
  tests/lib.rs
Labels: complexity::low, component::cli, type::idea, priority::low

#168 Adds prototype registry storage
  .github/workflows/cli.yml
  .github/workflows/registry.yml
  Cargo.lock
  registry/Cargo.toml
  registry/Proto.toml
  registry/deny.toml
  registry/docker-compose.yml
  registry/migrations/20230828111733_users.up.sql
  registry/migrations/20230828111844_packages.up.sql
  registry/proto/registry.proto
  registry/proto/resolver.proto
  registry/proto/version.proto
  registry/src/api.rs
  registry/src/api/grpc.rs
  registry/src/context.rs
  registry/src/db.rs
  registry/src/lib.rs
  registry/src/main.rs
  registry/src/options.rs
  registry/src/proto.rs
  registry/src/storage.rs
  registry/src/storage/filesystem.rs
  registry/src/storage/s3.rs
  registry/src/types.rs
  registry/tests/storage/filesystem.rs
  registry/tests/storage/main.rs
  registry/tests/storage/s3.rs
  tests/cmd/package/out/lib-0.0.1.tgz
Labels: datamodel, component::registry, priority::high, complexity::medium
