Repository helsing-ai/buffrs, pull requests merged in 2024-02, with the labels that each got.

#220 Removing dependency to git2
  Cargo.lock
  Cargo.toml
  src/command.rs
  tests/cmd/publish/stdout.log
  tests/cmd/tuto/mod.rs
Labels: complexity::low, component::cli, integration, priority::low, type::fix

#226 Nix Integration
  .github/workflows/ci.yml
  .github/workflows/nix.yml
  .github/workflows/nix_ci_ubuntu.yml
  Cargo.lock
  Cargo.toml
  docs/src/SUMMARY.md
  docs/src/commands/buffrs-generate.md
  docs/src/commands/buffrs-list.md
  docs/src/commands/buffrs-lock-print-files.md
  docs/src/commands/buffrs-package.md
  docs/src/commands/buffrs-publish.md
  docs/src/commands/build-commands.md
  docs/src/commands/index.md
  docs/src/integrations/cargo.md
  docs/src/integrations/index.md
  flake.nix
  nix/cache.nix
  registry/Cargo.toml
  registry/build.rs
  registry/docker-compose.yml
  registry/migrations/up.sh
  registry/src/proto.rs
  registry/tests/api/main.rs
  src/cache.rs
  src/command.rs
  src/credentials.rs
  src/generator.rs
  src/lib.rs
  src/lock.rs
  src/main.rs
  src/manifest.rs
  src/package/compressed.rs
  src/resolver.rs
  tests/cmd/add/out/Proto.toml
  tests/cmd/init/api/out/Proto.toml
  tests/cmd/init/default/out/Proto.toml
  tests/cmd/init/lib/out/Proto.toml
  tests/cmd/package/out/lib-0.0.1.tgz
  tests/cmd/publish/stdout.log
  tests/cmd/tuto/in/Cargo.toml
  tests/cmd/tuto/in/build.rs
  tests/cmd/tuto/in/main.rs
  tests/cmd/tuto/mod.rs
  tests/data/projects/lib/Proto.toml
Labels: docs::crate, datamodel, component::cli, priority::high, integration, complexity::high, type::epic, docs::book, docs::project

#228 Repair flake status
  README.md
Labels: complexity::low, type::style, priority::low, type::fix
